### ISSUE TITLE
have to include Eigen separately

### ISSUE THREAD

**Issue by kruesip** [ethz-asl/ethzasl_icp_mapping#10]
In order to use the `PointMatcher<float>::DataPoints` structure, I need to include Eigen separately:

    #include <Eigen/Dense>
    #include "pointmatcher/PointMatcher.h"

If if the first line is omitted, the compiler complains about Eigen stuff that is "not declared in this scope".

**Comment by pomerlef** [comment]
@kruesip is that still an issue?

**Comment by kruesip** [comment]
@pomerlef no, seems to be solved

**Comment by yuguo-Jack** [comment]
@kruesip I just want to know how to solve that problem, because i have the same problem now, thanks

**Comment by bryantaoli** [comment]
@kruesip I just want to know how to solve that problem, because i have the same problem now, thanks
