### ISSUE TITLE
this package has no catkin_version?

### ISSUE THREAD

**Issue by lligen** [ethz-asl/ethzasl_icp_mapping#29]
this package has no catkin_version?

**Comment by gawela** [comment]
Please checkout the indigo_devel or indigo_devel_time_support branch. It should contain what you are looking for.

**Comment by lligen** [comment]
i find no CMakeLists.txt  in indigo_devel or indigo_devel_time_support branch,  is this a package?  or what?

**Comment by gawela** [comment]
It was ported from a former rosbuild stack. You should be able to clone one of the indigo_devel branches into your catkin_ws and catkin build it from there. Catkin should recursively find the packages of ethz_icp_mapping.
