### ISSUE TITLE
Any SLAM solution available here?

### ISSUE THREAD

**Issue by baishibona** [ethz-asl/ethzasl_icp_mapping#43]
Hi,

I was wondering is there any consideration of a SLAM solution build on top of 3D scan matching?
Right now I am trying to put it together with iSAM which enable us to update the map by using key frames. I wasn't quite sure if you guys have developed that function or it is under developing?

Thanks.

**Comment by pomerlef** [comment]
Right now, there is none. We manage to go pretty far without global relaxation, so it wasn't a priority.

Recent results:
https://www.youtube.com/watch?v=jlAArM_6N-I

**Comment by baishibona** [comment]
That's a cool video, however we were using the puck, which is not as powerful as 64E, and we did have errors while the robot was in a forest like environment.
Could you point me to the function in ethzasl_icp_mapper that I can call for a scan matching between two point clouds (ideally ROS point cloud msg or just point cloud object)?

Thanks!

**Comment by pomerlef** [comment]
The conversion of pointcloud2 to our format (essentially a big Eigen matrix) is done [here](https://github.com/ethz-asl/ethzasl_icp_mapping/blob/master/ethzasl_icp_mapper/src/dynamic_mapper.cpp#L425). It looks more complicated than how it could be used:
```
DP points = PointMatcher_ros::rosMsgToPointMatcherCloud<float>(cloudMsgIn);
```

The ICP part happen [here](https://github.com/ethz-asl/ethzasl_icp_mapping/blob/master/ethzasl_icp_mapper/src/dynamic_mapper.cpp#L566). The object `icp` used here hold internal a map and is from the class `ICPSequence` defined in [libpointmatcher](https://github.com/ethz-asl/libpointmatcher).

This repository is mainly supported for our research partners and our changing needs. We have less time for public support right now.

**Comment by baishibona** [comment]
Thank you very much! I think I should be able to sort it out.

2016-05-11 17:57 GMT-04:00 François Pomerleau <notifications@github.com>:
