### ISSUE TITLE
support for Velodyne HDL-32e?

### ISSUE THREAD

**Issue by Chambana** [ethz-asl/ethzasl_icp_mapping#62]
The launch files have support for the 64-laser Velodyne and the Velodyne puck, but no explicit option to use the HDL-32e.

**Comment by pomerlef** [comment]
Look for the launch files in the folder Artor. That robot was equipped with a HDL-32e

**Comment by Chambana** [comment]
Terrific.  Do you remember if the Artor setup required a separate IMU for SLAM?  I only have the Velodyne data....

**Comment by liuqi8827** [comment]
@pomerlef Hi,
Dose the package support for VLP-16 (Velodyne 16)?

best

**Comment by pomerlef** [comment]
The node support anything producing a pointCloud2 message. How you tune it to work, that's up to you.

You can have a look at `ethzasl_icp_mapper/launch/velodyne_puck/` as a starting point.

**Comment by liuqi8827** [comment]
@pomerlef 
I've got it.

Tanks for your kind and prompt reply.
