### ISSUE TITLE
Real time processing

### ISSUE THREAD

**Issue by swarmt** [ethz-asl/ethzasl_icp_mapping#67]
Thanks for the excellent library. 
I am getting a lot of warnings about real time perfomance using the vlp16 launch files and filters. Could you please point me in the right direction for which filters to tune with the best performance increase and least accuracy lost?

**Comment by pomerlef** [comment]
That depends a lot on your application and your processing power. For slow motions, skipping few scans is not a problem. 

Typically, reducing the number of points helps. Random sampling is fast to compute, but it's blind to the structure of your scan. Density filtering is slower, but will yield more stable results with fewer points.

**Comment by swarmt** [comment]
Great thanks. I will tinker with those!
