### ISSUE TITLE
covariance of pose generated by icp mapper

### ISSUE THREAD

**Issue by SubMishMar** [ethz-asl/ethzasl_icp_mapping#76]
Is there any way to obtain the covariance associated with the pose output?

**Comment by PhiBabin** [comment]
`libpointmatcher` provided [someway of estimating the covariance](https://github.com/ethz-asl/libpointmatcher/blob/master/pointmatcher/ErrorMinimizers/PointToPlaneWithCov.cpp#L168) when `PointToPlaneWithCov` or `PointToPointWithCov` are used . You need to call the `icp.errorMinimizer->getCovariance()`.

Please take note that this estimate of the covariance an implementation of [this paper (Censis, 2007)](https://ieeexplore.ieee.org/document/4209579). My lab recently did some tests on this estimate for 3D datasets and we discover that it was quite erronous, see [this paper](https://arxiv.org/abs/1810.01470) and [this thesis](http://hdl.handle.net/20.500.11794/34734) for more information.
